name:  "GivTCP-BETA"
description:  "TCP Modbus connection to MQTT/JSON for Givenergy Battery/PV Invertors"
version:  "2.4.656"
image: britkat/giv_tcp-beta
slug:  "givtcp-beta"
homeassistant_api: true
hassio_api: true
init:  true
ingress: true
services:
  - "mqtt:want"
map:
  - config:rw
boot:  auto
url:  https://github.com/britkat1980/giv_tcp
legacy:  true
arch: 
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
host_network: true