name:  "GivTCP-DEV"
description:  "TCP Modbus connection to MQTT/JSON for Givenergy Battery/PV Invertors"
version:  "2.4.257"
image: britkat/giv_tcp-dev
slug:  "givtcp-dev"
homeassistant_api: true
hassio_api: true
init:  true
ingress: true
services:
  - "mqtt:want"
map:
  - config:rw
boot:  auto
url:  https://github.com/britkat1980/giv_tcp
legacy:  true
arch: 
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
host_network: true
options:
  NUMINVERTORS: 1
  INVERTOR_IP_1:  ""
  INVERTOR_NAME_1: "Inv1"
  HADEVICEPREFIX: "GivTCP"
  INVERTOR_IP_2:  ""
  INVERTOR_NAME_2: "Inv2"
  HADEVICEPREFIX_2: "GivTCP2"
  INVERTOR_IP_3:  ""
  INVERTOR_NAME_3: "Inv3"
  HADEVICEPREFIX_3: "GivTCP3"
  INVERTOR_IP_4:  ""
  INVERTOR_NAME_4: "Inv4"
  HADEVICEPREFIX_4: "GivTCP4"
  LOG_LEVEL: "Info"
  SELF_RUN_LOOP_TIMER: 30
  SELF_RUN_LOOP_TIMER_FULL: 120
  DYNAMICTARIFF: False
  DAYRATE: "0.155"
  NIGHTRATE: "0.055"
  EXPORTRATE: "0.04"
  DAYRATESTART: "04:30"
  NIGHTRATESTART: "00:30"
  INFLUX_OUTPUT: False
  INFLUX_URL: ""
  INFLUX_TOKEN: ""
  INFLUX_BUCKET: ""
  INFLUX_ORG: ""
  WEB_DASH: False
  WEB_DASH_PORT: 3000
  DATASMOOTHER: "medium"
  SMARTTARGET: False
  PALM_WINTER: "01,02,11,12"
  PALM_SHOULDER: "03,04,09,10"
  PALM_MIN_SOC_TARGET: 25
  PALM_MAX_SOC_TARGET: 45
  PALM_BATT_RESERVE: 4
  PALM_BATT_UTILISATION: 0.85
  PALM_WEIGHT: 35
  GEAPI: ""
  SOLCASTAPI: ""
  SOLCASTSITEID: ""
  SOLCASTSITEID2: ""
  LOAD_HIST_WEIGHT: "1"
  EVC_ENABLE: False
  EVC_IP_ADDRESS: ""
  EVC_SELF_RUN_TIMER: 5
schema: 
  NUMINVERTORS: int
  INVERTOR_IP_1:  str
  INVERTOR_NAME_1: str
  HADEVICEPREFIX: "str?"
  INVERTOR_IP_2:  "str?"
  INVERTOR_NAME_2: "str?"
  HADEVICEPREFIX_2: "str?"
  INVERTOR_IP_3:  "str?"
  INVERTOR_NAME_3: "str?"
  HADEVICEPREFIX_3: "str?"
  INVERTOR_IP_4:  "str?"
  INVERTOR_NAME_4: "str?"
  HADEVICEPREFIX_4: "str?"
  LOG_LEVEL: str
  SELF_RUN_LOOP_TIMER: int
  SELF_RUN_LOOP_TIMER_FULL: int
  DYNAMICTARIFF: bool
  DAYRATE: "str?"
  NIGHTRATE: "str?"
  EXPORTRATE: "str?"
  DAYRATESTART: "str?"
  NIGHTRATESTART: "str?"
  INFLUX_OUTPUT: bool
  INFLUX_URL: "str?"
  INFLUX_TOKEN: "str?"
  INFLUX_BUCKET: "str?"
  INFLUX_ORG: "str?"
  WEB_DASH: bool
  WEB_DASH_PORT: int
  DATASMOOTHER: "str?"
  SMARTTARGET: bool
  PALM_WINTER: "str"
  PALM_SHOULDER: "str"
  PALM_MIN_SOC_TARGET: int
  PALM_MAX_SOC_TARGET: int
  PALM_BATT_RESERVE: int
  PALM_BATT_UTILISATION: float
  PALM_WEIGHT: float
  GEAPI: "str?"
  SOLCASTAPI: "str?"
  SOLCASTSITEID: "str?"
  SOLCASTSITEID2: "str?"
  LOAD_HIST_WEIGHT: "str?"
  EVC_ENABLE: bool
  EVC_IP_ADDRESS: "str?"
  EVC_SELF_RUN_TIMER: int